env:
  version: 0.2.0
  vendor: rhomobile
  bbver: 4.6
  applog: rholog.txt
  symbian:
    certname: rhodes_cert.cer
    certkey: rhodes_pid.key
    certpwd: 1234
    selfsignname: "CN=Anton OU=Development OR=RhoMobile CO=RU EM=anton@rhomobile.com"
    selfsignpwd: "1234"
  paths:
    4.6:
      jde: C:/Program Files/Research In Motion/BlackBerry JDE 4.6.0
      java: C:/Program Files/Java/jdk1.6.0_11/bin
      mds: C:/Program Files/Research In Motion/BlackBerry JDE 4.6.0/MDS
      sim: 9000
    4.2:
      jde: C:/Program Files/Research In Motion/BlackBerry JDE 4.2.0 
      java: C:/Install/Java/jdk1.6.0_11/bin
      mds: C:/Program Files/Research In Motion/BlackBerry Email and MDS Services Simulators 4.1.2/MDS
      sim: 8100
    cabwiz: C:/Program Files/Windows Mobile 6 SDK/Tools/CabWiz/cabwiz.exe
    wmemu: C:/Program Files/Microsoft Device Emulator/1.0/dvcemumanager.exe
    symbiantools: C:/PROGRA~1/COMMON~1/Symbian/Tools
    symroot: C:/Symbian/9.2/S60_3rd_FP1


